import { artist, db, series, video } from "astro:db";
import seriesData from "./data/series.json";
import artistsData from "./data/artists.json";
import videosData from "./data/videos.json";

// Seeds the real ifyoumakeit.com archive, imported from the legacy
// production database. The JSON files in db/data/ are generated by
// `node scripts/import-legacy.mjs path/to/iymi_db.sql` — edit the data
// there (or re-run the importer), not here.
//
// The `song`, `tag`, and `videoTag` tables exist in the schema but have no
// legacy data: the video title IS the song title on the old site, and the
// legacy tags table was unusable. Pages hide those sections when empty.
export default async function seed() {
  await db.insert(series).values(seriesData);

  await db.insert(artist).values(artistsData);

  // libSQL caps SQL variables per statement; insert videos in chunks.
  const rows = videosData.map((v) => ({
    ...v,
    recorded_at: new Date(v.recorded_at),
  }));
  const CHUNK = 50;
  for (let i = 0; i < rows.length; i += CHUNK) {
    await db.insert(video).values(rows.slice(i, i + CHUNK));
  }
}
